import Head from 'next/head'
import Banner from '../components/Banner';
import ProductList from '../components/ProductList';
import axios from 'axios'

export default function Home({data}) {


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={``}>
        <Banner/>
        <ProductList allProducts={data}/>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await axios.get(`http://localhost:3000/api/products`);
  

  return {
    props: {
      data: res.data,
    },
  };
}
