import Head from "next/head";
import Banner from "../components/Banner";
import ProductList from "../components/ProductList";
import { QueryClient } from "react-query";
import { dehydrate } from "react-query/hydration";
import { useEffect } from "react";

const fetchData = async () => {
  const res = await fetch("https://pizza-house-omega.vercel.app/api/products");
  const data = await res.json();
  return data;
};

export default function Home({ dehydratedState }) {
  // const { data } = useQuery('products', fetchData);

  const data = dehydratedState?.queries[0]?.state?.data;
console.log(data);
  useEffect(() => {
    if (!data.length) {
      location.reload();
    }
  }, [data]);

  if (!data.length) {
    return (
      <div className="min-h-screen w-full flex justify-center items-center text-4xl font-bold">
        <div className="w-20 h-20 mx-auto border-4 border-dashed border-black rounded-full animate-spin"></div>
      </div>
    );
  }

  return (
    <div>
      <Head>
        <title>Pizza House</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={``}>
        <Banner />
        <ProductList allProducts={data} />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery("products", fetchData);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}
